name: IMG
version: 0.3.3
date: 19/09/2022
description: Computations with iterated monodromy groups

authors:
    - name: Laurent Bartholdi
      url: http://www.math.uni-sb.de/ag/bartholdi

maintainers:
    - name: Laurent Bartholdi
      url: http://www.math.uni-sb.de/ag/bartholdi

GAP: ">=4.6.0"

needed-pkgs:
    - name: "FR"
      version: ">=2.0.0"
      url: "https://gap-packages.github.io/fr"
    - name: "GAPDoc"
      version: ">=1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">=4.0"
      url: "https://gap-packages.github.io/io"

suggested-pkgs:
    - name: "Float"
      version: ">=0.4"
      url: "https://gap-packages.github.io/float/"

www: https://gap-packages.github.io/IMG
readme: README.md
packageinfo: https://gap-packages.github.io/IMG/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/img/releases/download/v0.3.3/IMG-0.3.3.tar.gz

abstract: The <span class="pkgname">IMG</span> package allows    GAP to manipulate iterated monodromy groups

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
