


.PHONY:   hurwitz

all: hurwitz


hurwitz:
	svn co https://centerfocus.svn.sourceforge.net/svnroot/centerfocus/rationalFunctionSearch/macaulay2-packages macaulay2-packages
	$(MAKE) -C macaulay2-packages install;
	
